### ISSUE TITLE
Announcement process

### ISSUE THREAD

**Issue by YannickB** [xpansa/community-web#5]
Hello Oleg,
Hope you’re doing great. 
We still have in the 25% left to integrate the flow of a proposition, right?
The process of an announcement
1/First i answer, so only quantity, when, unit price and description. With my picture and my name
2/ Then the announcer validates or not my answer  (footer/banner and he can make an answer)
3/ if it is validated, i could make the payment (change the price) and rate the transaction (rating, indicator type and feedback)
4/ the announcer could also at the same time rate the transaction (rating, indicator type and feedback) and ask for payment (bill to send).
Yannick made this process clear in the backend and it works in the front for articles. Do you need more information about this element? 
A few comments, not so prior
Make a reply
1/ I would like to go down to my future answer, in my block
2/ It is better if it is ordered from the newest to the latest, so my reply should be just under the announcement.
3/ The block size is too big on the screen
4/ Description field should be longer than that
5/ Add a reply should be in the banner/footer   (like every action buttons in the future)
Almost the end of our first part, I will send you very specific improvements to evaluate at the beginning of next week.
Thanks for your patience and work,
Julien

Hi Oleg,
On this point, we just need you display the workflow button like on the backoffice. You can see the code at https://github.com/YannickB/community-management/blob/master/marketplace/marketplace_view.xml lines 164 to 179.
Yannick.

**Comment by okuryan** [comment]
Yannick,

Here is update from us:
We've added workflow buttons, but we thinks it needs check from your side because at website proposition workflow looks a bit different from backend.
Within this issue we've fixed proposition currency line saving according to your comment:
"Here is what I was thinking :
-We have wallet lines in account.wallet.transaction, marketplace.announcement, marketplace.proposition and we will also have them in the crowdfunding which will come later. 
Then, I created only one object account.wallet.currency.line and I use it in all object, using model/res_id/field fields to link them to the records
-marketplace.proposition inherit account.wallet.transaction, so it also inherit currency_ids that's why I didn't add it in currency_ids. Normally it shall work correctly just make sure in res_id you specify the id of transaction_id field and not the id of the proposition."

Now it should work correct way.

The important note for you: as I we see now res.partner.wallet.balance model does not have explicit access rights and rules, that makes obstacles during some workflow buttons handling (some of them changes res.partner.wallet.balance entities).

**Comment by YannickB** [comment]
Ok I take the note, I'll correct this when I see it happen to me

Most transition correctly work now, thank you but some of them are still missing :

Missing : 
button name="proposition_draft_cancel" states="draft" string="Cancel"/>
button name="proposition_draft_open" states="draft" class="oe_highlight" string="Publish"/>
button name="proposition_open_cancel" states="open" string="Cancel"/>
button name="reset_workflow" states="cancel" string="Put in draft" type="object"/>
button name="reset_workflow" states="rejected" string="Put in draft" type="object"/>
button name="reset_workflow" states="paid" string="Refund" type="object"/>
button name="proposition_confirm_refund_paid" states="confirm_refund" string="Return to paid"/>
button name="proposition_confirm_refund_cancel" states="confirm_refund" class="oe_highlight" string="Confirm that you received the payment for the refund"/>

Done : 
button name="proposition_open_accepted" states="open" class="oe_highlight" string="Accept"/>
button name="proposition_open_rejected" states="open" class="oe_highlight" string="Reject"/>
button name="proposition_accepted_cancel" string="Cancel" attrs="{'invisible':['|','|','want_cancel_announcer', '!=', True),('want_cancel_user', '!=', True), ('state', '!=', 'accepted')]}"/>
button name="proposition_accepted_invoiced" states="accepted" class="oe_highlight" string="Invoice"/>
button name="proposition_invoiced_cancel" string="Cancel" attrs="{'invisible':['|','|',('want_cancel_announcer', '!=', True),('want_cancel_user', '!=', True), ('state', '!=', 'invoiced')]}"/>
button name="pay" states="invoiced" class="oe_highlight" string="Pay" type="object"/>
button name="confirm" states="confirm" class="oe_highlight" string="Confirm that you received the payment" type="object"/>

Also a state field similar to the one in announcement will be very handy.
You showed me the way so I'll probably be able to finish this ticket, I suggest you continue working on more important one.

**Comment by YannickB** [comment]
I'll start working on adding the missing transitions

**Comment by YannickB** [comment]
Ok with this all transitions are done. I let it open until #18 is done to make sure the whole workflow is working
